name: Build and Release EXE

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: 'windows-latest'
            name: 'windows'
          - os: 'ubuntu-latest'
            name: 'ubuntu-latest'
          - os: 'ubuntu-20.04'
            name: 'ubuntu-20.04'
          - os: 'macos-latest'
            name: 'macos'

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install system dependencies (Linux)
      if: startsWith(matrix.os, 'ubuntu-')
      run: |
        sudo apt-get update
        sudo apt-get install -y libxcb-xinerama0 libxcb-cursor0 libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-shape0 libxcb-xfixes0 libopengl0

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install certifi  # Ensure certifi is installed

    - name: Locate certifi CA bundle
      id: certifi
      shell: bash
      run: |
        echo "CERTIFI_CA_BUNDLE=$(python -m certifi)" >> $GITHUB_ENV

    - name: Build application
      shell: bash
      run: |
        echo "CERTIFI_CA_BUNDLE: $CERTIFI_CA_BUNDLE"
        if [ "${{ matrix.os }}" == "windows-latest" ]; then
          pyinstaller --noconsole --onefile --add-data "$CERTIFI_CA_BUNDLE;certifi" --hidden-import=PyQt6.QtCore --hidden-import=PyQt6.QtGui --hidden-import=PyQt6.QtWidgets --name video_downloader main.py
          mv dist/video_downloader.exe video_downloader_windows.exe
        elif [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
          export QT_QPA_PLATFORM=offscreen
          pyinstaller --noconsole --onefile --add-data "$CERTIFI_CA_BUNDLE:certifi" --hidden-import=PyQt6.QtCore --hidden-import=PyQt6.QtGui --hidden-import=PyQt6.QtWidgets --name video_downloader main.py
          mv dist/video_downloader video_downloader_linux.bin
          chmod +x video_downloader_linux.bin
        elif [ "${{ matrix.os }}" == "ubuntu-20.04" ]; then
          export QT_QPA_PLATFORM=offscreen
          pyinstaller --noconsole --onefile --add-data "$CERTIFI_CA_BUNDLE:certifi" --hidden-import=PyQt6.QtCore --hidden-import=PyQt6.QtGui --hidden-import=PyQt6.QtWidgets --name video_downloader main.py
          mv dist/video_downloader video_downloader_linux_ubuntu20.04.bin
          chmod +x video_downloader_linux_ubuntu20.04.bin
        elif [ "${{ matrix.os }}" == "macos-latest" ]; then
          pyinstaller --noconsole --onefile --add-data "$CERTIFI_CA_BUNDLE:certifi" --hidden-import=PyQt6.QtCore --hidden-import=PyQt6.QtGui --hidden-import=PyQt6.QtWidgets --name video_downloader main.py
          mv dist/video_downloader video_downloader_macos
          chmod +x video_downloader_macos
        fi

    - name: Upload Windows artifact
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: video_downloader_${{ matrix.os }}
        path: video_downloader_windows.exe

    - name: Upload Linux artifact (Latest)
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: video_downloader_${{ matrix.os }}
        path: video_downloader_linux.bin

    - name: Upload Linux artifact (Ubuntu 20.04 LTS)
      if: matrix.os == 'ubuntu-20.04'
      uses: actions/upload-artifact@v4
      with:
        name: video_downloader_${{ matrix.os }}
        path: video_downloader_linux_ubuntu20.04.bin

    - name: Upload macOS artifact
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        name: video_downloader_${{ matrix.os }}
        path: video_downloader_macos


  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download Windows artifact
      uses: actions/download-artifact@v4
      with:
        name: video_downloader_windows-latest

    - name: Download Linux artifact (Latest)
      uses: actions/download-artifact@v4
      with:
        name: video_downloader_ubuntu-latest

    - name: Download Linux artifact (Ubuntu 20.04 LTS)
      uses: actions/download-artifact@v4
      with:
        name: video_downloader_ubuntu-20.04

    - name: Download macOS artifact
      uses: actions/download-artifact@v4
      with:
        name: video_downloader_macos-latest

    - name: Publish Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: |
          video_downloader_windows.exe
          video_downloader_linux.bin
          video_downloader_linux_ubuntu20.04.bin
          video_downloader_macos
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |
          A new release is available.
          - Includes builds for Windows, Linux (Latest), Linux (Ubuntu 20.04 LTS), and macOS.
          
          **Linux Users:**
          - Use `video_downloader_linux.bin` for Ubuntu 22.04+ and other modern distributions
          - Use `video_downloader_linux_ubuntu20.04.bin` for Ubuntu 20.04 LTS and compatible older systems
